name: Assign self to Pull Request

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  assign:
    name: Assign self to pull request
    runs-on: ubuntu-latest
    steps:
      - name: Assign self to pull request
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
